### ISSUE TITLE
How to use this plugin?

### ISSUE THREAD

**Issue by FineSrss** [jweslley/sentry-googlechat#2]
I want Alerts should support Google Chat WebHooks...
but i can't find google chat plugin.

how to use sentry-googlechat plugin?

this is my legacy integrations list.
![sentry_legacy_integrations](https://user-images.githubusercontent.com/17739078/120286797-98bb7780-c2f9-11eb-9c53-eeb3cbbf5c81.jpg)

**Comment by jweslley** [comment]
We need to install it on your sentry instance. PLease follow this for more information https://github.com/jweslley/sentry-googlechat#installation
